language: python
python:
  - "3.6"
script:
  - coverage run --source='TelegramBot' -m unittest discover -s tests -t tests
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
after_success:
  - coveralls
